services:
  kafka:
    build: 
      context: .
      dockerfile: kafka.dockerfile
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - kafka:/var/lib/kafka/data
    
volumes:
  kafka: